version: "3.9"
services:
  ticket-service:
    build: ./ticket-service
    ports:
      - "8000:8000"
    restart: always
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    restart: always
